/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InTheLoopRouteImport } from './routes/in-the-loop'
import { Route as IndexRouteImport } from './routes/index'

const InTheLoopRoute = InTheLoopRouteImport.update({
  id: '/in-the-loop',
  path: '/in-the-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/in-the-loop': typeof InTheLoopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/in-the-loop': typeof InTheLoopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/in-the-loop': typeof InTheLoopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/in-the-loop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/in-the-loop'
  id: '__root__' | '/' | '/in-the-loop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InTheLoopRoute: typeof InTheLoopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/in-the-loop': {
      id: '/in-the-loop'
      path: '/in-the-loop'
      fullPath: '/in-the-loop'
      preLoaderRoute: typeof InTheLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InTheLoopRoute: InTheLoopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
